#!/bin/bash

puaq(){ # puaq stands for Print Usage And Quit
    echo "Usage: `basename $0` new_repo_name"
    if [ "$1" = true ]; then
        exit 0
    else
        exit 1
    fi
}

if [ -z $1 ]; then
    puaq false
fi

NEW_REPO_NAME=$1

if [ -e $NEW_REPO_NAME ]; then
    echo "Path [$NEW_REPO_NAME] already exists."
    exit 1
fi

mkdir $NEW_REPO_NAME
cd $NEW_REPO_NAME
git init --bare
NEW_REPO_FULL_PATH=(`pwd -P`)
sendtoclipboard.py $NEW_REPO_FULL_PATH
echo "Sent path [$NEW_REPO_FULL_PATH] to the clipboard."
