#!/bin/bash

TARGET=""

if [ -z $1 ]; then
  # target repo not specified. lets use current working dir
  TARGET=`pwd -P`
else
  # target repo has been specified. lets use it
  TARGET=$1
fi

# mvtodo: test if .git isnt already specified in the end
# mvtodo: if this is is a subfolder of a parent repo, also resolve to it
TARGET=${TARGET}/.git

gipus_all_remotes_current_branch.py $TARGET

