#!/bin/bash

TARGET=""

if [ -z $1 ]; then
  # target repo not specified. lets use current working dir
  TARGET=`pwd -P`
  TARGET=${TARGET}/.git
else
  # target repo has been specified. lets resolve it and use it
  TARGET=$1
fi

gipus_all_remotes_current_branch.py $TARGET

