#!/bin/bash

TARGET=""

if [ -z $1 ]; then
  # target repo not specified. lets use current working dir
  TARGET=`pwd -P`
else
  # target repo has been specified. lets use it
  TARGET=$1
fi

# mvtodo: check if below is necessary (if hasnt been specified by user already and whatnot)
TARGET=${TARGET}/.git

gipul_all_remotes_current_branch.py $TARGET

