#!/bin/bash

alias gidif_setgui="git config --global diff.external meldiff.py"
alias gidif_setcmd="git config --global --unset diff.external"
alias gidif="git diff"

alias gicom="git commit" # mvtodo: add mvtags checking as a precondition

alias gichepi="git cherry-pick"

alias gista="git status"
alias giadd="git add"
alias girem="git rm"
alias gilog="git log"
alias gipus="git push"
alias gipul="git pull"
alias giclo="git clone"
alias gibra="git branch"
alias giche="git checkout"
alias gires="git reset"
alias gimer="git merge"
alias gifet="git fetch"
alias gitag="git tag"
alias gisub="git submodule"
alias gireb="git rebase"
alias gibis="git bisect"
alias giapp="git apply"
alias gides="git describe"
alias gisho="git show"
alias giini="git init"
alias gicon="git config"
alias gitag="git tag"
alias gireb="git rebase"
alias girem="git remote"
alias gigre="git grep -n"
alias gihel="git help"
alias gibla="git blame"
alias giash="git stash"
alias giver="git version"

alias gimv="git mv"
alias girm="git rm"
