#!/bin/bash

puaq(){ # puaq stands for Print Usage And Quit
  echo "Usage: `basename $0` base_path"
  exit 1
}

TARGET=$1

if [ -z $TARGET ]; then
  puaq
fi

if [ ! -e $TARGET ]; then
  echo "$TARGET does not exist. Aborting."
  exit 1
fi

git_visitor_pull.py $TARGET

