#!/bin/bash

TARGET=""

if [ -z $1 ]; then
    # target repo not specified. lets use current working dir
    TARGET=`pwd -P`
else
    # target repo has been specified. lets use it
    TARGET=$1
fi

TARGET=(`git_discover_repo_root.py $TARGET`) # resolve to the actual repo
#gifet_all.py $TARGET
git_sub_pull.py $TARGET
