#!/bin/bash

REPO_BASE=""
EXTRA_OPTION=""

if [ ! -z $1 ]; then
    REPO_BASE="$1"
fi

if [ "$REPO_BASE" == "." ]; then
    REPO_BASE=`pwd -P`
fi

if [ ! -z $REPO_BASE ]; then
    EXTRA_OPTION="--repo-base $REPO_BASE"
fi

git_visitor_push.py --not-remotename offline $EXTRA_OPTION

